---
- name: Setting datetime
  hosts: all
  become: true
  vars:
    datetime: "Nov 22 9:00:00 1996"

  tasks:
    - name: Disable network time setting
      shell: timedatectl set-ntp no

    - name: Set date
      shell: date --set "{{datetime}}"

    - name: Check datetime
      shell: date
      register: r
    - debug: msg="{{r.stdout}}"

    